### ISSUE TITLE
Implement automatic loading and storing of packages

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_minr#4]
Use the approach outlined here: https://github.com/aronlindberg/lab_notebook/blob/master/2015-09-20-scripting-templates.md

For packages not on CRAN, we'll use `try` or `try_default` from here: http://www.inside-r.org/packages/cran/plyr/docs/try_default

We can use:

devtools::install_github("cscheid/rgithub")

**Comment by chandini6** [comment]
This is resolved by #8 pull request
