### ISSUE TITLE
Make the rgithub based code run properly

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_minr#7]
It may necessitate making either changes to the code or commits to the rgithub project itself.

**Comment by chandini6** [comment]
I have checked with the 1st functions while running the code, The digester head link functions runs without any errors, there are few errors while calling the function which are resolved ,
these are the following errors with the comment function
1. attempt to use zero-length variable name near  if (number_of_pages ``````````````````!= 0)
2.Try default function in r
3. commits object is not found 
4. syntax error related to '}'

**Comment by aronlindberg** [comment]
1. is a typo and 2. is because `try_default` is part of the `plyr` package which has to be loaded. 3. and 4. may simply follow from these first two errors.

**Comment by aronlindberg** [comment]
Here are some helpful advice on how to build the package locally: https://support.rstudio.com/hc/en-us/articles/200486508-Building-Testing-and-Distributing-Packages
